# Configurações de Produção
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate

# Banner Customizado
spring.banner.location=classpath:banner-prod.txt

# Logging
logging.level.psicologia.clinica=INFO
